[[plugins]]
  package = "netlify-plugin-flutter"

[build]
  base = "frontend"
  command = "flutter build web --release --dart-define=API_BASE_URL=https://songwork-api.onrender.com"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"
